-- MySQL Script generated by MySQL Workbench
-- Wed Mar 23 15:55:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cul_d_ampolla
-- -----------------------------------------------------
-- Optica

-- -----------------------------------------------------
-- Schema cul_d_ampolla
--
-- Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cul_d_ampolla` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `cul_d_ampolla` ;

-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`proveedores` (
  `proveedores_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(4) NOT NULL,
  `piso` VARCHAR(3) NOT NULL,
  `puerta` VARCHAR(3) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`proveedores_id`),
  INDEX `index_NIF` (`NIF` ASC) VISIBLE,
  INDEX `index_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`clientes` (
  `clientes_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `cliente_recomendado` VARCHAR(90) NULL,
  `fecha_registro` DATE NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(4) NOT NULL,
  `piso` VARCHAR(3) NOT NULL,
  `puerta` VARCHAR(3) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(5) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`clientes_id`),
  INDEX `index_nombre` (`nombre` ASC) INVISIBLE,
  INDEX `index_apellido` (`apellidos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`empleados` (
  `empleados_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`empleados_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`factura` (
  `factura_id` INT NOT NULL AUTO_INCREMENT,
  `empleados_empleados_id` INT NOT NULL,
  `clientes_clientes_id` INT NOT NULL,
  PRIMARY KEY (`factura_id`, `empleados_empleados_id`, `clientes_clientes_id`),
  INDEX `fk_ventas_empleados_idx` (`empleados_empleados_id` ASC) VISIBLE,
  INDEX `fk_ventas_clientes1_idx` (`clientes_clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_empleados`
    FOREIGN KEY (`empleados_empleados_id`)
    REFERENCES `cul_d_ampolla`.`empleados` (`empleados_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`clientes_clientes_id`)
    REFERENCES `cul_d_ampolla`.`clientes` (`clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`gafas` (
  `gafas_id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacion_dch` DECIMAL NOT NULL COMMENT 'Graduación cristal derecho',
  `graduacion_izq` DECIMAL NOT NULL COMMENT 'Graduación cristal izquierdo',
  `tipo_montura` VARCHAR(1) NOT NULL COMMENT 'Opciones:\nF=Flotante\nP=Pasta\nM=Metálida',
  `proveedores_proveedores_id` INT NOT NULL,
  `factura_factura_id` INT NOT NULL,
  PRIMARY KEY (`gafas_id`, `factura_factura_id`),
  INDEX `index_marca` (`marca` ASC) VISIBLE,
  INDEX `fk_gafas_proveedores1_idx` (`proveedores_proveedores_id` ASC) VISIBLE,
  INDEX `fk_gafas_factura1_idx` (`factura_factura_id` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_proveedores1`
    FOREIGN KEY (`proveedores_proveedores_id`)
    REFERENCES `cul_d_ampolla`.`proveedores` (`proveedores_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gafas_factura1`
    FOREIGN KEY (`factura_factura_id`)
    REFERENCES `cul_d_ampolla`.`factura` (`factura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
